--- Configure packer and list plugins
require("vorb.plugins-setup")
require("vorb.core.colorscheme")
require("vorb.core.options")
require("vorb.core.keymaps")
require("vorb.plugins.comment")
require("vorb.plugins.nvim-tree")
require("vorb.plugins.lualine")
require("vorb.plugins.telescope")
require("vorb.plugins.treesitter")
require("vorb.plugins.nvim-cmp")
require("vorb.plugins.lsp.mason")
require("vorb.plugins.lsp.null-ls")
require("vorb.plugins.lsp.lspsaga")
require("vorb.plugins.lsp.lspconfig")
require("vorb.plugins.gitsigns")
require("vorb.plugins.autopairs")
